version: '3.8'

services:
  app:
    image: alpine-container
    build: ./  # Build context
    container_name: app_container
    ports:
      - "8089:8089"  # Serveur configuré sur le port 8089
    environment:
      # Correspondance avec application.properties
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Remplacez par le mot de passe si nécessaire
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
      SPRING_JPA_SHOW_SQL: "true"
      LOGGING_LEVEL_ROOT: info
      LOGGING_PATTERN_CONSOLE: =%d{yyyy-MM-dd HH:mm:ss} -  %-5level- %logger{45} - %msg %n
      SERVER_SERVLET_CONTEXT_PATH: /events
      SERVER_PORT: 8089
      SPRING_MVC_FORMAT_DATE: yyyy-MM-dd
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Remplacez par le mot de passe si nécessaire
      MYSQL_DATABASE: eventsProject  # Correspond au nom de la base de données
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:  # Définition du volume pour la base de données
